# Generated by Django 4.2.7 on 2024-04-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('apellido', models.CharField(help_text='Apellido', max_length=50)),
                ('dni', models.IntegerField(help_text='DNI')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('precio', models.FloatField(help_text='Precio')),
                ('stock_actual', models.IntegerField(help_text='Stock Actual')),
                ('proveedor', models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, to='compra.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
