# Generated by Django 4.2.7 on 2024-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_producto_nombre_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(),
        ),
    ]
